(ns milfin.chains)

(def chains
  [{:rpc
  ["https://mainnet.infura.io/v3/${INFURA_API_KEY}"
   "wss://mainnet.infura.io/ws/v3/${INFURA_API_KEY}"
   "https://api.mycryptoapi.com/eth"
   "https://cloudflare-eth.com"],
  :nativeCurrency {:name "Ether", :symbol "ETH", :decimals 18},
  :explorers
  [{:name "etherscan",
    :url "https://etherscan.io",
    :standard "EIP3091"}],
  :name "Ethereum Mainnet",
  :faucets [],
  :shortName "eth",
  :chainId 1,
  :chain "ETH",
  :network "mainnet",
  :infoURL "https://ethereum.org",
  :networkId 1}
 {:rpc ["https://mainnet.optimism.io/"],
  :nativeCurrency {:name "Ether", :symbol "OETH", :decimals 18},
  :explorers [],
  :name "Optimistic Ethereum",
  :faucets [],
  :shortName "oeth",
  :chainId 10,
  :chain "ETH",
  :network "mainnet",
  :infoURL "https://optimism.io",
  :networkId 10}
 {:rpc
  ["https://rpc.xdaichain.com"
   "https://xdai.poanetwork.dev"
   "wss://rpc.xdaichain.com/wss"
   "wss://xdai.poanetwork.dev/wss"
   "http://xdai.poanetwork.dev"
   "https://dai.poa.network"
   "ws://xdai.poanetwork.dev:8546"],
  :nativeCurrency {:name "xDAI", :symbol "xDAI", :decimals 18},
  :explorers [],
  :name "xDAI Chain",
  :faucets [],
  :shortName "xdai",
  :chainId 100,
  :chain "XDAI",
  :network "mainnet",
  :infoURL "https://forum.poa.network/c/xdai-chain",
  :networkId 100}
 {:rpc ["https://node-api.klaytnapi.com/v1/klaytn"],
  :nativeCurrency {:name "KLAY", :symbol "KLAY", :decimals 18},
  :explorers [],
  :name "Klaytn Testnet Baobab",
  :faucets ["https://baobab.wallet.klaytn.com/access?next=faucet"],
  :shortName "Baobab",
  :chainId 1001,
  :chain "KLAY",
  :network "baobab",
  :infoURL "https://www.klaytn.com/",
  :networkId 1001}
 {:rpc ["https://rpc1.newchain.newtonproject.org"],
  :nativeCurrency {:name "Newton", :symbol "NEW", :decimals 18},
  :explorers [],
  :name "Newton Testnet",
  :faucets [],
  :shortName "tnew",
  :chainId 1007,
  :chain "NEW",
  :network "testnet",
  :infoURL "https://www.newtonproject.org/",
  :networkId 1007}
 {:rpc ["https://api.einc.io/jsonrpc/mainnet"],
  :nativeCurrency
  {:name "EtherInc Ether", :symbol "ETI", :decimals 18},
  :explorers [],
  :name "EtherInc",
  :faucets [],
  :shortName "eti",
  :chainId 101,
  :chain "ETI",
  :network "mainnet",
  :infoURL "https://einc.io",
  :networkId 1}
 {:rpc ["https://meta.evrice.com"],
  :nativeCurrency {:name "Evrice", :symbol "EVC", :decimals 18},
  :explorers [],
  :name "Evrice Network",
  :faucets [],
  :shortName "EVC",
  :chainId 1010,
  :chain "EVC",
  :network "Evrice",
  :infoURL "https://evrice.com",
  :networkId 1010}
 {:rpc ["https://global.rpc.mainnet.newtonproject.org"],
  :nativeCurrency {:name "Newton", :symbol "NEW", :decimals 18},
  :explorers [],
  :name "Newton",
  :faucets [],
  :shortName "new",
  :chainId 1012,
  :chain "NEW",
  :network "mainnet",
  :infoURL "https://www.newtonproject.org/",
  :networkId 1012}
 {:rpc ["https://substrate.org.cn"],
  :nativeCurrency {:name "SGC", :symbol "SGC", :decimals 18},
  :explorers [],
  :name "SGC Testnet",
  :faucets [],
  :shortName "sgc",
  :chainId 102,
  :chain "SGC",
  :network "SGC testnet",
  :infoURL "https://web3games.blockspaper.com/en/",
  :networkId 102}
 {:rpc [],
  :nativeCurrency {:name "Clover", :symbol "CLV", :decimals 18},
  :explorers [],
  :name "Clover Testnet",
  :faucets [],
  :shortName "tclv",
  :chainId 1023,
  :chain "Clover",
  :network "clover testnet",
  :infoURL "https://clover.finance",
  :networkId 1023}
 {:rpc [],
  :nativeCurrency {:name "Clover", :symbol "CLV", :decimals 18},
  :explorers [],
  :name "Clover Mainnet",
  :faucets [],
  :shortName "clv",
  :chainId 1024,
  :chain "Clover",
  :network "clover mainnet",
  :infoURL "https://clover.finance",
  :networkId 1024}
 {:rpc ["https://mainnet-rpc.thundercore.com"],
  :nativeCurrency
  {:name "ThunderCore Mainnet Ether", :symbol "TT", :decimals 18},
  :explorers [],
  :name "ThunderCore Mainnet",
  :faucets ["https://faucet.thundercore.com"],
  :shortName "TT",
  :chainId 108,
  :chain "TT",
  :network "mainnet",
  :infoURL "https://thundercore.com",
  :networkId 108}
 {:rpc ["https://api.metadium.com/prod"],
  :nativeCurrency
  {:name "Metadium Mainnet Ether", :symbol "META", :decimals 18},
  :explorers [],
  :name "Metadium Mainnet",
  :faucets [],
  :shortName "meta",
  :chainId 11,
  :chain "META",
  :network "mainnet",
  :infoURL "https://metadium.com",
  :networkId 11}
 {:rpc ["https://rpc.iposlab.com" "https://rpc2.iposlab.com"],
  :nativeCurrency
  {:name "IPOS Network Ether", :symbol "IPOS", :decimals 18},
  :explorers [],
  :name "IPOS Network",
  :faucets [],
  :shortName "ipos",
  :chainId 1122334455,
  :chain "IPOS",
  :network "mainnet",
  :infoURL "https://iposlab.com",
  :networkId 1122334455}
 {:rpc [],
  :nativeCurrency {:name "MathChain", :symbol "MATH", :decimals 18},
  :explorers [],
  :name "MathChain",
  :faucets [],
  :shortName "MATH",
  :chainId 1139,
  :chain "MATH",
  :network "mainnet",
  :infoURL "https://mathchain.org",
  :networkId 1139}
 {:rpc ["https://galois-hk.maiziqianbao.net/rpc"],
  :nativeCurrency {:name "MathChain", :symbol "MATH", :decimals 18},
  :explorers [],
  :name "MathChain Testnet",
  :faucets ["https://scan.boka.network/#/Galois/faucet"],
  :shortName "tMATH",
  :chainId 1140,
  :chain "MATH",
  :network "testnet",
  :infoURL "https://mathchain.org",
  :networkId 1140}
 {:rpc ["https://api.metadium.com/dev"],
  :nativeCurrency
  {:name "Metadium Testnet Ether", :symbol "KAL", :decimals 18},
  :explorers [],
  :name "Metadium Testnet",
  :faucets [],
  :shortName "kal",
  :chainId 12,
  :chain "META",
  :network "testnet",
  :infoURL "https://metadium.com",
  :networkId 12}
 {:rpc ["https://rpc.fuse.io"],
  :nativeCurrency {:name "Fuse", :symbol "FUSE", :decimals 18},
  :explorers [],
  :name "Fuse Mainnet",
  :faucets [],
  :shortName "fuse",
  :chainId 122,
  :chain "FUSE",
  :network "mainnet",
  :infoURL "https://fuse.io/",
  :networkId 122}
 {:rpc
  ["https://http-mainnet.hecochain.com"
   "wss://ws-mainnet.hecochain.com"],
  :nativeCurrency
  {:name "Huobi ECO Chain Native Token", :symbol "HT", :decimals 18},
  :explorers [],
  :name "Huobi ECO Chain Mainnet",
  :faucets [],
  :shortName "heco",
  :chainId 128,
  :chain "Heco",
  :network "mainnet",
  :infoURL "https://hecoinfo.com",
  :networkId 128}
 {:rpc [],
  :nativeCurrency {:name "Glimmer", :symbol "GLMR", :decimals 18},
  :explorers [],
  :name "Moonbeam Polkadot",
  :faucets [],
  :shortName "mbeam",
  :chainId 1284,
  :chain "MOON",
  :network "moonbeam",
  :infoURL "https://moonbeam.network/networks/moonbeam/",
  :networkId 1284}
 {:rpc [],
  :nativeCurrency {:name "River", :symbol "RIVER", :decimals 18},
  :explorers [],
  :name "Moonriver Kusama",
  :faucets [],
  :shortName "mriver",
  :chainId 1285,
  :chain "MOON",
  :network "moonriver",
  :infoURL "https://moonbeam.network/networks/moonriver/",
  :networkId 1285}
 {:rpc [],
  :nativeCurrency {:name "Rocs", :symbol "ROC", :decimals 18},
  :explorers [],
  :name "Moonrock Rococo",
  :faucets [],
  :shortName "mrock",
  :chainId 1286,
  :chain "MOON",
  :network "moonrock",
  :infoURL "",
  :networkId 1286}
 {:rpc
  ["https://rpc.testnet.moonbeam.network"
   "wss://wss.testnet.moonbeam.network"],
  :nativeCurrency {:name "Dev", :symbol "DEV", :decimals 18},
  :explorers [],
  :name "Moonbeam Testnet Moonbase Alpha",
  :faucets [],
  :shortName "mbase",
  :chainId 1287,
  :chain "MOON",
  :network "moonbase",
  :infoURL "https://docs.moonbeam.network/networks/testnet/",
  :networkId 1287}
 {:rpc
  ["https://staging.diode.io:8443/" "wss://staging.diode.io:8443/ws"],
  :nativeCurrency
  {:name "Staging Diodes", :symbol "sDIODE", :decimals 18},
  :explorers [],
  :name "Diode Testnet Staging",
  :faucets [],
  :shortName "dstg",
  :chainId 13,
  :chain "DIODE",
  :network "testnet",
  :infoURL "https://diode.io/staging",
  :networkId 13}
 {:rpc ["https://rpc.ether1.org"],
  :nativeCurrency
  {:name "Ether-1 Ether", :symbol "ETHO", :decimals 18},
  :explorers [],
  :name "Ether-1",
  :faucets [],
  :shortName "etho",
  :chainId 1313114,
  :chain "ETHO",
  :network "mainnet",
  :infoURL "https://ether1.org",
  :networkId 1313114}
 {:rpc [],
  :nativeCurrency {:name "NEAR", :symbol "NEAR", :decimals 24},
  :explorers [],
  :name "NEAR MainNet",
  :faucets [],
  :shortName "near",
  :chainId 1313161554,
  :chain "NEAR",
  :network "mainnet",
  :infoURL "https://near.org/",
  :networkId 1313161554}
 {:rpc [],
  :nativeCurrency {:name "NEAR", :symbol "tNEAR", :decimals 24},
  :explorers [],
  :name "NEAR TestNet",
  :faucets ["https://wallet.testnet.near.org"],
  :shortName "neart",
  :chainId 1313161555,
  :chain "NEAR",
  :network "testnet",
  :infoURL "https://near.org/",
  :networkId 1313161555}
 {:rpc [],
  :nativeCurrency {:name "NEAR", :symbol "bNEAR", :decimals 24},
  :explorers [],
  :name "NEAR BetaNet",
  :faucets [],
  :shortName "nearb",
  :chainId 1313161556,
  :chain "NEAR",
  :network "betanet",
  :infoURL "https://near.org/",
  :networkId 1313161556}
 {:rpc ["https://rpc.xerom.org"],
  :nativeCurrency {:name "Xerom Ether", :symbol "XERO", :decimals 18},
  :explorers [],
  :name "Xerom",
  :faucets [],
  :shortName "xero",
  :chainId 1313500,
  :chain "XERO",
  :network "mainnet",
  :infoURL "https://xerom.org",
  :networkId 1313500}
 {:rpc ["https://churchill-rpc.pepchain.io"],
  :nativeCurrency
  {:name "PepChain Churchill Ether", :symbol "TPEP", :decimals 18},
  :explorers [],
  :name "PepChain Churchill",
  :faucets [],
  :shortName "tpep",
  :chainId 13371337,
  :chain "PEP",
  :network "testnet",
  :infoURL "https://pepchain.io",
  :networkId 13371337}
 {:rpc
  ["https://rpc-mainnet.matic.network"
   "wss://ws-mainnet.matic.network"],
  :nativeCurrency {:name "Matic", :symbol "MATIC", :decimals 18},
  :explorers [],
  :name "Matic Mainnet",
  :faucets [],
  :shortName "matic",
  :chainId 137,
  :chain "Matic",
  :network "mainnet",
  :infoURL "https://matic.network/",
  :networkId 137}
 {:rpc [],
  :nativeCurrency {:name "Spark", :symbol "FLR", :decimals 18},
  :explorers [],
  :name "Flare Mainnet",
  :faucets [],
  :shortName "flr",
  :chainId 14,
  :chain "FLR",
  :network "flare",
  :infoURL "https://flare.xyz",
  :networkId 14}
 {:rpc
  ["https://prenet.diode.io:8443/" "wss://prenet.diode.io:8443/ws"],
  :nativeCurrency {:name "Diodes", :symbol "DIODE", :decimals 18},
  :explorers [],
  :name "Diode Prenet",
  :faucets [],
  :shortName "diode",
  :chainId 15,
  :chain "DIODE",
  :network "mainnet",
  :infoURL "https://diode.io/prenet",
  :networkId 15}
 {:rpc [],
  :nativeCurrency {:name "Coston Spark", :symbol "CFLR", :decimals 18},
  :explorers [],
  :name "Flare Testnet Coston",
  :faucets [],
  :shortName "cflr",
  :chainId 16,
  :chain "FLR",
  :network "coston",
  :infoURL "https://github.com/flare-eng/coston",
  :networkId 16}
 {:rpc ["https://node.sirius.lightstreams.io"],
  :nativeCurrency
  {:name "Lightstreams PHT", :symbol "PHT", :decimals 18},
  :explorers [],
  :name "Lightstreams Testnet",
  :faucets
  ["https://discuss.lightstreams.network/t/request-test-tokens"],
  :shortName "tpht",
  :chainId 162,
  :chain "PHT",
  :network "sirius",
  :infoURL "https://explorer.sirius.lightstreams.io",
  :networkId 162}
 {:rpc ["https://wallet.atheios.com:8797"],
  :nativeCurrency {:name "Atheios Ether", :symbol "ATH", :decimals 18},
  :explorers [],
  :name "Atheios",
  :faucets [],
  :shortName "ath",
  :chainId 1620,
  :chain "ATH",
  :network "mainnet",
  :infoURL "https://atheios.com",
  :networkId 11235813}
 {:rpc ["https://node.mainnet.lightstreams.io"],
  :nativeCurrency
  {:name "Lightstreams PHT", :symbol "PHT", :decimals 18},
  :explorers [],
  :name "Lightstreams Mainnet",
  :faucets [],
  :shortName "pht",
  :chainId 163,
  :chain "PHT",
  :network "mainnet",
  :infoURL "https://explorer.lightstreams.io",
  :networkId 163}
 {:rpc ["https://api.harmony.one"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Mainnet Shard 0",
  :faucets [],
  :shortName "hmy-s0",
  :chainId 1666600000,
  :chain "Harmony",
  :network "mainnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666600000}
 {:rpc ["https://s1.api.harmony.one"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Mainnet Shard 1",
  :faucets [],
  :shortName "hmy-s1",
  :chainId 1666600001,
  :chain "Harmony",
  :network "mainnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666600001}
 {:rpc ["https://s2.api.harmony.one"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Mainnet Shard 2",
  :faucets [],
  :shortName "hmy-s2",
  :chainId 1666600002,
  :chain "Harmony",
  :network "mainnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666600002}
 {:rpc ["https://s3.api.harmony.one"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Mainnet Shard 3",
  :faucets [],
  :shortName "hmy-s3",
  :chainId 1666600003,
  :chain "Harmony",
  :network "mainnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666600003}
 {:rpc ["https://api.s0.b.hmny.io"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Testnet Shard 0",
  :faucets [],
  :shortName "hmy-b-s0",
  :chainId 1666700000,
  :chain "Harmony",
  :network "testnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666700000}
 {:rpc ["https://api.s1.b.hmny.io"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Testnet Shard 1",
  :faucets [],
  :shortName "hmy-b-s1",
  :chainId 1666700001,
  :chain "Harmony",
  :network "testnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666700001}
 {:rpc ["https://api.s2.b.hmny.io"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Testnet Shard 2",
  :faucets [],
  :shortName "hmy-b-s2",
  :chainId 1666700002,
  :chain "Harmony",
  :network "testnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666700002}
 {:rpc ["https://api.s3.b.hmny.io"],
  :nativeCurrency {:name "ONE", :symbol "ONE", :decimals 18},
  :explorers [],
  :name "Harmony Testnet Shard 3",
  :faucets [],
  :shortName "hmy-b-s3",
  :chainId 1666700003,
  :chain "Harmony",
  :network "testnet",
  :infoURL "https://www.harmony.one/",
  :networkId 1666700003}
 {:rpc ["https://rpc.thaifi.com"],
  :nativeCurrency {:name "Thaifi Ether", :symbol "TFI", :decimals 18},
  :explorers [],
  :name "ThaiChain 2.0 ThaiFi",
  :faucets [],
  :shortName "tfi",
  :chainId 17,
  :chain "TCH",
  :network "thaifi",
  :infoURL "https://exp.thaifi.com",
  :networkId 17}
 {:rpc ["https://testnet-rpc.thundercore.com"],
  :nativeCurrency
  {:name "ThunderCore Testnet Ether", :symbol "TST", :decimals 18},
  :explorers [],
  :name "ThunderCore Testnet",
  :faucets ["https://faucet-testnet.thundercore.com"],
  :shortName "TST",
  :chainId 18,
  :chain "TST",
  :network "testnet",
  :infoURL "https://thundercore.com",
  :networkId 18}
 {:rpc ["https://net.iolite.io"],
  :nativeCurrency {:name "IOLite Ether", :symbol "ILT", :decimals 18},
  :explorers [],
  :name "IOLite",
  :faucets [],
  :shortName "ilt",
  :chainId 18289463,
  :chain "ILT",
  :network "mainnet",
  :infoURL "https://iolite.io",
  :networkId 18289463}
 {:rpc ["https://tsfapi.europool.me"],
  :nativeCurrency
  {:name "Teslafunds Ether", :symbol "TSF", :decimals 18},
  :explorers [],
  :name "Teslafunds",
  :faucets [],
  :shortName "tsf",
  :chainId 1856,
  :chain "TSF",
  :network "mainnet",
  :infoURL "https://teslafunds.io",
  :networkId 1}
 {:rpc ["https://jsonrpc.egem.io/custom"],
  :nativeCurrency
  {:name "EtherGem Ether", :symbol "EGEM", :decimals 18},
  :explorers [],
  :name "EtherGem",
  :faucets [],
  :shortName "egem",
  :chainId 1987,
  :chain "EGEM",
  :network "mainnet",
  :infoURL "https://egem.io",
  :networkId 1987}
 {:rpc ["https://node.expanse.tech"],
  :nativeCurrency
  {:name "Expanse Network Ether", :symbol "EXP", :decimals 18},
  :explorers [],
  :name "Expanse Network",
  :faucets [],
  :shortName "exp",
  :chainId 2,
  :chain "EXP",
  :network "mainnet",
  :infoURL "https://expanse.tech",
  :networkId 1}
 {:rpc ["https://mainrpc.elaeth.io"],
  :nativeCurrency {:name "Elastos", :symbol "ELA", :decimals 18},
  :explorers [],
  :name "ELA-ETH-Sidechain Mainnet",
  :faucets [],
  :shortName "elaeth",
  :chainId 20,
  :chain "ETH",
  :network "mainnet",
  :infoURL "https://www.elastos.org/",
  :networkId 20}
 {:rpc ["https://remote.akroma.io"],
  :nativeCurrency {:name "Akroma Ether", :symbol "AKA", :decimals 18},
  :explorers [],
  :name "Akroma",
  :faucets [],
  :shortName "aka",
  :chainId 200625,
  :chain "AKA",
  :network "mainnet",
  :infoURL "https://akroma.io",
  :networkId 200625}
 {:rpc [],
  :nativeCurrency {:name "Fourtwenty", :symbol "420", :decimals 18},
  :explorers [],
  :name "420coin",
  :faucets [],
  :shortName "420",
  :chainId 2020,
  :chain "420",
  :network "mainnet",
  :infoURL "https://420integrated.com",
  :networkId 2020}
 {:rpc ["https://mainnet1.edgewa.re"],
  :nativeCurrency {:name "Edge", :symbol "EDG", :decimals 18},
  :explorers [],
  :name "Edgeware Mainnet",
  :faucets [],
  :shortName "edg",
  :chainId 2021,
  :chain "EDG",
  :network "mainnet",
  :infoURL "http://edgewa.re",
  :networkId 2021}
 {:rpc ["https://beresheet1.edgewa.re"],
  :nativeCurrency {:name "Testnet Edge", :symbol "tEDG", :decimals 18},
  :explorers [],
  :name "Beresheet Testnet",
  :faucets [],
  :shortName "edgt",
  :chainId 2022,
  :chain "EDG",
  :network "beresheet",
  :infoURL "http://edgewa.re",
  :networkId 2022}
 {:rpc ["https://rpc.elaeth.io"],
  :nativeCurrency {:name "Elastos", :symbol "tELA", :decimals 18},
  :explorers [],
  :name "ELA-ETH-Sidechain Testnet",
  :faucets ["https://faucet.elaeth.io/"],
  :shortName "elaetht",
  :chainId 21,
  :chain "ETH",
  :network "testnet",
  :infoURL "https://elaeth.io/",
  :networkId 21}
 {:rpc
  ["http://13.57.207.168:3435"
   "https://app.freighttrust.net/ftn/${API_KEY}"],
  :nativeCurrency
  {:name "Freight Trust Native", :symbol "0xF", :decimals 18},
  :explorers [],
  :name "Freight Trust Network",
  :faucets ["http://faucet.freight.sh"],
  :shortName "EDI",
  :chainId 211,
  :chain "EDI",
  :network "freight & trade network",
  :infoURL "https://freighttrust.com",
  :networkId 0}
 {:rpc [],
  :nativeCurrency {:name "Elastos", :symbol "ELA", :decimals 18},
  :explorers [],
  :name "ELA-DID-Sidechain Mainnet",
  :faucets [],
  :shortName "eladid",
  :chainId 22,
  :chain "ETH",
  :network "mainnet",
  :infoURL "https://www.elastos.org/",
  :networkId 22}
 {:rpc [],
  :nativeCurrency {:name "Elastos", :symbol "tELA", :decimals 18},
  :explorers [],
  :name "ELA-DID-Sidechain Testnet",
  :faucets [],
  :shortName "eladidt",
  :chainId 23,
  :chain "ETH",
  :network "testnet",
  :infoURL "https://elaeth.io/",
  :networkId 23}
 {:rpc ["https://node1.webchain.network"],
  :nativeCurrency
  {:name "Webchain Ether", :symbol "WEB", :decimals 18},
  :explorers [],
  :name "Webchain",
  :faucets [],
  :shortName "web",
  :chainId 24484,
  :chain "WEB",
  :network "mainnet",
  :infoURL "https://webchain.network",
  :networkId 37129}
 {:rpc ["https://rpc.energyweb.org" "wss://rpc.energyweb.org/ws"],
  :nativeCurrency
  {:name "Energy Web Token", :symbol "EWT", :decimals 18},
  :explorers [],
  :name "Energy Web Chain",
  :faucets [],
  :shortName "ewt",
  :chainId 246,
  :chain "Energy Web Chain",
  :network "mainnet",
  :infoURL "https://energyweb.org",
  :networkId 246}
 {:rpc ["https://rpc.sigma1.artis.network"],
  :nativeCurrency
  {:name "ARTIS sigma1 Ether", :symbol "ATS", :decimals 18},
  :explorers [],
  :name "ARTIS sigma1",
  :faucets [],
  :shortName "ats",
  :chainId 246529,
  :chain "ARTIS",
  :network "sigma1",
  :infoURL "https://artis.eco",
  :networkId 246529}
 {:rpc ["https://rpc.tau1.artis.network"],
  :nativeCurrency
  {:name "ARTIS tau1 Ether", :symbol "tATS", :decimals 18},
  :explorers [],
  :name "ARTIS Testnet tau1",
  :faucets [],
  :shortName "atstau",
  :chainId 246785,
  :chain "ARTIS",
  :network "tau1",
  :infoURL "https://artis.network",
  :networkId 246785}
 {:rpc ["https://node1.mintme.com"],
  :nativeCurrency
  {:name "MintMe.com Coin", :symbol "MINTME", :decimals 18},
  :explorers [],
  :name "MintMe.com Coin",
  :faucets [],
  :shortName "mintme",
  :chainId 24734,
  :chain "MINTME",
  :network "mainnet",
  :infoURL "https://www.mintme.com",
  :networkId 37480}
 {:rpc ["https://rpcapi.fantom.network" "https://fantomscan.io/rpc"],
  :nativeCurrency {:name "Fantom", :symbol "FTM", :decimals 18},
  :explorers [],
  :name "Fantom Opera",
  :faucets [],
  :shortName "ftm",
  :chainId 250,
  :chain "FTM",
  :network "mainnet",
  :infoURL "https://fantom.foundation",
  :networkId 250}
 {:rpc
  ["https://http-testnet.hecochain.com"
   "wss://ws-testnet.hecochain.com"],
  :nativeCurrency
  {:name "Huobi ECO Chain Test Native Token",
   :symbol "htt",
   :decimals 18},
  :explorers [],
  :name "Huobi ECO Chain Testnet",
  :faucets ["https://scan-testnet.hecochain.com/faucet"],
  :shortName "hecot",
  :chainId 256,
  :chain "Heco",
  :network "testnet",
  :infoURL "https://testnet.hecoinfo.com",
  :networkId 256}
 {:rpc ["https://hpb.app"],
  :nativeCurrency
  {:name "High Performance Blockchain Ether",
   :symbol "HPB",
   :decimals 18},
  :explorers [],
  :name "High Performance Blockchain",
  :faucets [],
  :shortName "hpb",
  :chainId 269,
  :chain "HPB",
  :network "mainnet",
  :infoURL "https://hpbscan.org/",
  :networkId 100}
 {:rpc ["https://rpc.auxilium.global"],
  :nativeCurrency {:name "Auxilium coin", :symbol "AUX", :decimals 18},
  :explorers [],
  :name "Auxilium Network Mainnet",
  :faucets [],
  :shortName "auxi",
  :chainId 28945486,
  :chain "AUX",
  :network "mainnet",
  :infoURL "https://auxilium.global",
  :networkId 28945486}
 {:rpc
  ["https://ropsten.infura.io/v3/${INFURA_API_KEY}"
   "wss://ropsten.infura.io/ws/v3/${INFURA_API_KEY}"],
  :nativeCurrency {:name "Ropsten Ether", :symbol "ROP", :decimals 18},
  :explorers [],
  :name "Ethereum Testnet Ropsten",
  :faucets ["https://faucet.ropsten.be?${ADDRESS}"],
  :shortName "rop",
  :chainId 3,
  :chain "ETH",
  :network "ropsten",
  :infoURL "https://github.com/ethereum/ropsten",
  :networkId 3}
 {:rpc ["https://public-node.rsk.co" "https://mycrypto.rsk.co"],
  :nativeCurrency
  {:name "RSK Mainnet Ether", :symbol "RBTC", :decimals 18},
  :explorers [],
  :name "RSK Mainnet",
  :faucets [],
  :shortName "rsk",
  :chainId 30,
  :chain "RSK",
  :network "mainnet",
  :infoURL "https://rsk.co",
  :networkId 30}
 {:rpc
  ["https://public-node.testnet.rsk.co"
   "https://mycrypto.testnet.rsk.co"],
  :nativeCurrency
  {:name "RSK Testnet Ether", :symbol "tRBTC", :decimals 18},
  :explorers [],
  :name "RSK Testnet",
  :faucets ["https://faucet.testnet.rsk.co"],
  :shortName "trsk",
  :chainId 31,
  :chain "RSK",
  :network "testnet",
  :infoURL "https://rsk.co",
  :networkId 31}
 {:rpc ["https://api.esn.gonspool.com"],
  :nativeCurrency
  {:name "Ethersocial Network Ether", :symbol "ESN", :decimals 18},
  :explorers [],
  :name "Ethersocial Network",
  :faucets [],
  :shortName "esn",
  :chainId 31102,
  :chain "ESN",
  :network "mainnet",
  :infoURL "https://ethersocial.org",
  :networkId 1}
 {:rpc ["https://wallrpc.pirl.io"],
  :nativeCurrency {:name "Pirl Ether", :symbol "PIRL", :decimals 18},
  :explorers [],
  :name "Pirl",
  :faucets [],
  :shortName "pirl",
  :chainId 3125659152,
  :chain "PIRL",
  :network "mainnet",
  :infoURL "https://pirl.io",
  :networkId 3125659152}
 {:rpc ["https://mainnet.anyswap.exchange" "https://fsn.dev/api"],
  :nativeCurrency {:name "Fusion", :symbol "FSN", :decimals 18},
  :explorers [],
  :name "Fusion Mainnet",
  :faucets [],
  :shortName "fsn",
  :chainId 32659,
  :chain "FSN",
  :network "mainnet",
  :infoURL "https://www.fusion.org/",
  :networkId 32659}
 {:rpc ["https://rpc.goodata.io"],
  :nativeCurrency
  {:name "GoodData Mainnet Ether", :symbol "GooD", :decimals 18},
  :explorers [],
  :name "GoodData Mainnet",
  :faucets [],
  :shortName "GooD",
  :chainId 33,
  :chain "GooD",
  :network "mainnet",
  :infoURL "https://www.goodata.org",
  :networkId 33}
 {:rpc ["https://rpc.tbwg.io"],
  :nativeCurrency {:name "TBWG Ether", :symbol "TBG", :decimals 18},
  :explorers [],
  :name "TBWG Chain",
  :faucets [],
  :shortName "tbwg",
  :chainId 35,
  :chain "TBWG",
  :network "mainnet",
  :infoURL "https://tbwg.io",
  :networkId 35}
 {:rpc ["https://node.joys.digital"],
  :nativeCurrency {:name "JOYS", :symbol "JOYS", :decimals 18},
  :explorers [],
  :name "Joys Digital Mainnet",
  :faucets [],
  :shortName "JOYS",
  :chainId 35855456,
  :chain "JOYS",
  :network "mainnet",
  :infoURL "https://joys.digital",
  :networkId 35855456}
 {:rpc ["https://rpc.valorbit.com/v2"],
  :nativeCurrency {:name "Valorbit", :symbol "VAL", :decimals 18},
  :explorers [],
  :name "Valorbit",
  :faucets [],
  :shortName "val",
  :chainId 38,
  :chain "VAL",
  :network "mainnet",
  :infoURL "https://valorbit.com",
  :networkId 38}
 {:rpc ["https://rpc-bitfalls1.lisinski.online"],
  :nativeCurrency
  {:name "Lisinski Ether", :symbol "LISINSKI", :decimals 18},
  :explorers [],
  :name "Lisinski",
  :faucets ["https://pipa.lisinski.online"],
  :shortName "lisinski",
  :chainId 385,
  :chain "CRO",
  :network "mainnet",
  :infoURL "https://lisinski.online",
  :networkId 385}
 {:rpc ["https://nodeapi.gen3.energi.network"],
  :nativeCurrency {:name "Energi", :symbol "NRG", :decimals 18},
  :explorers [],
  :name "Energi Mainnet",
  :faucets [],
  :shortName "nrg",
  :chainId 39797,
  :chain "NRG",
  :network "mainnet",
  :infoURL "https://www.energi.world/",
  :networkId 39797}
 {:rpc
  ["https://rinkeby.infura.io/v3/${INFURA_API_KEY}"
   "wss://rinkeby.infura.io/ws/v3/${INFURA_API_KEY}"],
  :nativeCurrency {:name "Rinkeby Ether", :symbol "RIN", :decimals 18},
  :explorers [],
  :name "Ethereum Testnet Rinkeby",
  :faucets ["https://faucet.rinkeby.io"],
  :shortName "rin",
  :chainId 4,
  :chain "ETH",
  :network "rinkeby",
  :infoURL "https://www.rinkeby.io",
  :networkId 4}
 {:rpc ["https://mainnet.telos.net/evm"],
  :nativeCurrency {:name "Telos", :symbol "TLOS", :decimals 18},
  :explorers [],
  :name "Telos EVM Mainnet",
  :faucets [],
  :shortName "Telos EVM",
  :chainId 40,
  :chain "TLOS",
  :network "mainnet",
  :infoURL "https://telos.net",
  :networkId 40}
 {:rpc ["https://testnet.telos.net/evm"],
  :nativeCurrency {:name "Telos", :symbol "TLOS", :decimals 18},
  :explorers [],
  :name "Telos EVM Testnet",
  :faucets ["https://app.telos.net/testnet/developers"],
  :shortName "Telos EVM Testnet",
  :chainId 41,
  :chain "TLOS",
  :network "testnet",
  :infoURL "https://telos.net",
  :networkId 41}
 {:rpc
  ["https://kovan.poa.network"
   "http://kovan.poa.network:8545"
   "https://kovan.infura.io/v3/${INFURA_API_KEY}"
   "wss://kovan.infura.io/ws/v3/${INFURA_API_KEY}"
   "ws://kovan.poa.network:8546"],
  :nativeCurrency {:name "Kovan Ether", :symbol "KOV", :decimals 18},
  :explorers [],
  :name "Ethereum Testnet Kovan",
  :faucets
  ["https://faucet.kovan.network"
   "https://gitter.im/kovan-testnet/faucet"],
  :shortName "kov",
  :chainId 42,
  :chain "ETH",
  :network "kovan",
  :infoURL "https://kovan-testnet.github.io/website",
  :networkId 42}
 {:rpc ["https://goerli.optimism.io/"],
  :nativeCurrency {:name "Görli Ether", :symbol "GOR", :decimals 18},
  :explorers [],
  :name "Optimistic Ethereum Testnet Goerli",
  :faucets [],
  :shortName "ogor",
  :chainId 420,
  :chain "ETH",
  :network "goerli",
  :infoURL "https://optimism.io",
  :networkId 420}
 {:rpc [],
  :nativeCurrency {:name "pegglecoin", :symbol "peggle", :decimals 18},
  :explorers [],
  :name "pegglecoin",
  :faucets [],
  :shortName "PC",
  :chainId 42069,
  :chain "42069",
  :network "mainnet",
  :infoURL "https://teampeggle.com",
  :networkId 42069}
 {:rpc ["https://forno.celo.org" "wss://forno.celo.org/ws"],
  :nativeCurrency {:name "CELO", :symbol "CELO", :decimals 18},
  :explorers [],
  :name "Celo Mainnet",
  :faucets [],
  :shortName "CELO",
  :chainId 42220,
  :chain "CELO",
  :network "Mainnet",
  :infoURL "https://docs.celo.org/",
  :networkId 42220}
 {:rpc [],
  :nativeCurrency
  {:name "Pangolin RING", :symbol "PRING", :decimals 9},
  :explorers [],
  :name "Darwinia Pangolin Testnet",
  :faucets [],
  :shortName "darwinia",
  :chainId 43,
  :chain "pangolin",
  :network "free testnet",
  :infoURL "https://darwinia.network/",
  :networkId 43}
 {:rpc ["https://ava.network:21015/ext/evm/rpc"],
  :nativeCurrency
  {:name "Athereum Ether", :symbol "ATH", :decimals 18},
  :explorers [],
  :name "Athereum",
  :faucets ["http://athfaucet.ava.network//?address=${ADDRESS}"],
  :shortName "avaeth",
  :chainId 43110,
  :chain "ATH",
  :network "athereum",
  :infoURL "https://athereum.ava.network",
  :networkId 43110}
 {:rpc ["https://api.avax-test.network/ext/bc/C/rpc"],
  :nativeCurrency {:name "Avalanche", :symbol "AVAX", :decimals 18},
  :explorers [],
  :name "Avalanche Fuji Testnet",
  :faucets ["https://faucet.avax-test.network/"],
  :shortName "Fuji",
  :chainId 43113,
  :chain "AVAX",
  :network "testnet",
  :infoURL "https://cchain.explorer.avax-test.network",
  :networkId 1}
 {:rpc ["https://api.avax.network/ext/bc/C/rpc"],
  :nativeCurrency {:name "Avalanche", :symbol "AVAX", :decimals 18},
  :explorers [],
  :name "Avalanche Mainnet",
  :faucets [],
  :shortName "Avalanche",
  :chainId 43114,
  :chain "AVAX",
  :network "mainnet",
  :infoURL "https://cchain.explorer.avax.network/",
  :networkId 1}
 {:rpc [],
  :nativeCurrency {:name "Crab Token", :symbol "CRING", :decimals 9},
  :explorers [],
  :name "Darwinia Crab Network",
  :faucets [],
  :shortName "crab",
  :chainId 44,
  :chain "crab",
  :network "Crab network",
  :infoURL "https://crab.network/",
  :networkId 44}
 {:rpc
  ["https://alfajores-forno.celo-testnet.org"
   "wss://alfajores-forno.celo-testnet.org/ws"],
  :nativeCurrency {:name "CELO", :symbol "CELO", :decimals 18},
  :explorers [],
  :name "Celo Alfajores Testnet",
  :faucets
  ["https://celo.org/developers/faucet"
   "https://cauldron.pretoriaresearchlab.io/alfajores-faucet"],
  :shortName "ALFA",
  :chainId 44787,
  :chain "CELO",
  :network "Alfajores",
  :infoURL "https://docs.celo.org/",
  :networkId 44787}
 {:rpc ["https://babel-api.mainnet.iotex.one"],
  :nativeCurrency {:name "IoTeX", :symbol "IOTX", :decimals 18},
  :explorers [],
  :name "IoTeX Network Mainnet",
  :faucets [],
  :shortName "iotex-mainnet",
  :chainId 4689,
  :chain "IOTX",
  :network "mainnet",
  :infoURL "https://iotex.io",
  :networkId 4689}
 {:rpc ["https://babel-api.testnet.iotex.one"],
  :nativeCurrency {:name "IoTeX", :symbol "IOTX", :decimals 18},
  :explorers [],
  :name "IoTeX Network Testnet",
  :faucets [],
  :shortName "iotex-testnet",
  :chainId 4690,
  :chain "IOTX",
  :network "testnet",
  :infoURL "https://iotex.io",
  :networkId 4690}
 {:rpc ["https://nodeapi.test3.energi.network"],
  :nativeCurrency {:name "Energi", :symbol "tNRG", :decimals 18},
  :explorers [],
  :name "Energi Testnet",
  :faucets [],
  :shortName "tnrg",
  :chainId 49797,
  :chain "NRG",
  :network "testnet",
  :infoURL "https://www.energi.world/",
  :networkId 49797}
 {:rpc [],
  :nativeCurrency {:name "Rupaya", :symbol "RUPX", :decimals 18},
  :explorers [],
  :name "Rupaya",
  :faucets [],
  :shortName "rupx",
  :chainId 499,
  :chain "RUPX",
  :network "mainnet",
  :infoURL "https://www.rupx.io",
  :networkId 499}
 {:rpc
  ["https://rpc.goerli.mudit.blog/"
   "https://rpc.slock.it/goerli "
   "https://goerli.prylabs.net/"],
  :nativeCurrency {:name "Görli Ether", :symbol "GOR", :decimals 18},
  :explorers [],
  :name "Ethereum Testnet Görli",
  :faucets
  ["https://goerli-faucet.slock.it/?address=${ADDRESS}"
   "https://faucet.goerli.mudit.blog"],
  :shortName "gor",
  :chainId 5,
  :chain "ETH",
  :network "goerli",
  :infoURL "https://goerli.net/#about",
  :networkId 5}
 {:rpc ["https://rpc.xinfin.network"],
  :nativeCurrency {:name "XinFin", :symbol "XDC", :decimals 18},
  :explorers [],
  :name "XinFin Network Mainnet",
  :faucets [],
  :shortName "xdc",
  :chainId 50,
  :chain "XDC",
  :network "mainnet",
  :infoURL "https://xinfin.org",
  :networkId 50}
 {:rpc ["https://rpc.apothem.network"],
  :nativeCurrency {:name "XinFinTest", :symbol "TXDC", :decimals 18},
  :explorers [],
  :name "XinFin Apothem Testnet",
  :faucets [],
  :shortName "TXDC",
  :chainId 51,
  :chain "TXDC",
  :network "testnet",
  :infoURL "https://xinfin.org",
  :networkId 51}
 {:rpc ["https://rpc-mainnet.coinex.net"],
  :nativeCurrency
  {:name "CoinEx Chain Native Token", :symbol "cet", :decimals 18},
  :explorers [],
  :name "CoinEx Smart Chain Mainnet",
  :faucets [],
  :shortName "cet",
  :chainId 52,
  :chain "CSC",
  :network "mainnet",
  :infoURL "http://www.coinex.org/",
  :networkId 52}
 {:rpc ["https://rpc-testnet.coinex.net"],
  :nativeCurrency
  {:name "CoinEx Chain Test Native Token",
   :symbol "cett",
   :decimals 18},
  :explorers [],
  :name "CoinEx Smart Chain Testnet",
  :faucets [],
  :shortName "tcet",
  :chainId 53,
  :chain "CSC",
  :network "testnet",
  :infoURL "http://www.coinex.org/",
  :networkId 53}
 {:rpc
  ["https://rpc.testnet.tao.network"
   "http://rpc.testnet.tao.network:8545"
   "https://rpc.tao.network"
   "wss://rpc.tao.network"],
  :nativeCurrency {:name "Tao", :symbol "TAO", :decimals 18},
  :explorers [],
  :name "Tao Network",
  :faucets [],
  :shortName "tao",
  :chainId 558,
  :chain "TAO",
  :network "core",
  :infoURL "https://tao.network",
  :networkId 558}
 {:rpc
  ["https://bsc-dataseed1.binance.org"
   "https://bsc-dataseed2.binance.org"
   "https://bsc-dataseed3.binance.org"
   "https://bsc-dataseed4.binance.org"
   "https://bsc-dataseed1.defibit.io"
   "https://bsc-dataseed2.defibit.io"
   "https://bsc-dataseed3.defibit.io"
   "https://bsc-dataseed4.defibit.io"
   "https://bsc-dataseed1.ninicoin.io"
   "https://bsc-dataseed2.ninicoin.io"
   "https://bsc-dataseed3.ninicoin.io"
   "https://bsc-dataseed4.ninicoin.io"
   "wss://bsc-ws-node.nariox.org"],
  :nativeCurrency
  {:name "Binance Chain Native Token", :symbol "BNB", :decimals 18},
  :explorers [],
  :name "Binance Smart Chain Mainnet",
  :faucets [],
  :shortName "bnb",
  :chainId 56,
  :chain "BSC",
  :network "mainnet",
  :infoURL "https://www.binance.org",
  :networkId 56}
 {:rpc
  ["https://proxy.wegochain.io" "http://wallet.wegochain.io:7764"],
  :nativeCurrency {:name "Rubid", :symbol "RBD", :decimals 18},
  :explorers [],
  :name "Wegochain Rubidium Mainnet",
  :faucets [],
  :shortName "rbd",
  :chainId 5869,
  :chain "RBD",
  :network "mainnet",
  :infoURL "http://wegochain.io",
  :networkId 5869}
 {:rpc [],
  :nativeCurrency
  {:name "Acala Mandala Token", :symbol "mACA", :decimals 18},
  :explorers [],
  :name "Acala Mandala Testnet",
  :faucets [],
  :shortName "maca",
  :chainId 595,
  :chain "mACA",
  :network "testnet",
  :infoURL "https://acala.network",
  :networkId 595}
 {:rpc [],
  :nativeCurrency {:name "Kotti Ether", :symbol "KOT", :decimals 18},
  :explorers [],
  :name "Ethereum Classic Testnet Kotti",
  :faucets [],
  :shortName "kot",
  :chainId 6,
  :chain "ETC",
  :network "kotti",
  :infoURL "https://explorer.jade.builders/?network=kotti",
  :networkId 6}
 {:rpc ["https://rpc.gochain.io"],
  :nativeCurrency {:name "GoChain Ether", :symbol "GO", :decimals 18},
  :explorers [],
  :name "GoChain",
  :faucets [],
  :shortName "go",
  :chainId 60,
  :chain "GO",
  :network "mainnet",
  :infoURL "https://gochain.io",
  :networkId 60}
 {:rpc ["https://ethereumclassic.network"],
  :nativeCurrency
  {:name "Ethereum Classic Ether", :symbol "ETC", :decimals 18},
  :explorers [],
  :name "Ethereum Classic Mainnet",
  :faucets [],
  :shortName "etc",
  :chainId 61,
  :chain "ETC",
  :network "mainnet",
  :infoURL "https://ethereumclassic.org",
  :networkId 1}
 {:rpc ["https://c.onical.org" "https://tx.aquacha.in/api"],
  :nativeCurrency
  {:name "Aquachain Ether", :symbol "AQUA", :decimals 18},
  :explorers [],
  :name "Aquachain",
  :faucets ["https://aquacha.in/faucet"],
  :shortName "aqua",
  :chainId 61717561,
  :chain "AQUA",
  :network "mainnet",
  :infoURL "https://aquachain.github.io",
  :networkId 61717561}
 {:rpc [],
  :nativeCurrency
  {:name "Ethereum Classic Testnet Ether",
   :symbol "TETC",
   :decimals 18},
  :explorers [],
  :name "Ethereum Classic Testnet Morden",
  :faucets [],
  :shortName "tetc",
  :chainId 62,
  :chain "ETC",
  :network "testnet",
  :infoURL "https://ethereumclassic.org",
  :networkId 2}
 {:rpc ["https://baklava-forno.celo-testnet.org"],
  :nativeCurrency {:name "CELO", :symbol "CELO", :decimals 18},
  :explorers [],
  :name "Celo Baklava Testnet",
  :faucets
  ["https://docs.google.com/forms/d/e/1FAIpQLSdfr1BwUTYepVmmvfVUDRCwALejZ-TUva2YujNpvrEmPAX2pg/viewform"
   "https://cauldron.pretoriaresearchlab.io/baklava-faucet"],
  :shortName "BKLV",
  :chainId 62320,
  :chain "CELO",
  :network "Baklava",
  :infoURL "https://docs.celo.org/",
  :networkId 62320}
 {:rpc [],
  :nativeCurrency
  {:name "Mordor Classic Testnet Ether", :symbol "METC", :decimals 18},
  :explorers [],
  :name "Ethereum Classic Testnet Mordor",
  :faucets [],
  :shortName "metc",
  :chainId 63,
  :chain "ETC",
  :network "testnet",
  :infoURL "https://github.com/eth-classic/mordor/",
  :networkId 7}
 {:rpc ["https://jsonrpc.ellaism.org"],
  :nativeCurrency
  {:name "Ellaism Ether", :symbol "ELLA", :decimals 18},
  :explorers [],
  :name "Ellaism",
  :faucets [],
  :shortName "ella",
  :chainId 64,
  :chain "ELLA",
  :network "mainnet",
  :infoURL "https://ellaism.org",
  :networkId 64}
 {:rpc ["https://exchaintestrpc.okex.org"],
  :nativeCurrency
  {:name "OKExChain Global Utility Token in testnet",
   :symbol "OKT",
   :decimals 18},
  :explorers [],
  :name "OKExChain Testnet",
  :faucets ["https://www.okex.com/drawdex"],
  :shortName "tokt",
  :chainId 65,
  :chain "okexchain",
  :network "testnet",
  :infoURL "https://www.okex.com/okexchain",
  :networkId 65}
 {:rpc ["https://exchainrpc.okex.org"],
  :nativeCurrency
  {:name "OKExChain Global Utility Token",
   :symbol "OKT",
   :decimals 18},
  :explorers [],
  :name "OKExChain Mainnet",
  :faucets [],
  :shortName "okt",
  :chainId 66,
  :chain "okexchain",
  :network "mainnet",
  :infoURL "https://www.okex.com/okexchain",
  :networkId 66}
 {:rpc ["http://test-rpc.dbmbp.com"],
  :nativeCurrency
  {:name "DBChain Testnet", :symbol "DBM", :decimals 18},
  :explorers [],
  :name "DBChain Testnet",
  :faucets [],
  :shortName "dbm",
  :chainId 67,
  :chain "DBM",
  :network "testnet",
  :infoURL "http://test.dbmbp.com",
  :networkId 67}
 {:rpc ["https://rpc.soter.one"],
  :nativeCurrency
  {:name "SoterOne Mainnet Ether", :symbol "SOTER", :decimals 18},
  :explorers [],
  :name "SoterOne Mainnet",
  :faucets [],
  :shortName "SO1",
  :chainId 68,
  :chain "SOTER",
  :network "mainnet",
  :infoURL "https://www.soterone.com",
  :networkId 68}
 {:rpc [],
  :nativeCurrency {:name "Karura Token", :symbol "KAR", :decimals 18},
  :explorers [],
  :name "Karura Network",
  :faucets [],
  :shortName "kar",
  :chainId 686,
  :chain "KAR",
  :network "mainnet",
  :infoURL "https://karura.network",
  :networkId 686}
 {:rpc ["https://kovan.optimism.io/"],
  :nativeCurrency {:name "Kovan Ether", :symbol "KOR", :decimals 18},
  :explorers [],
  :name "Optimistic Ethereum Testnet Kovan",
  :faucets [],
  :shortName "okov",
  :chainId 69,
  :chain "ETH",
  :network "kovan",
  :infoURL "https://optimism.io",
  :networkId 69}
 {:rpc ["https://rpc.dome.cloud"],
  :nativeCurrency
  {:name "ThaiChain Ether", :symbol "TCH", :decimals 18},
  :explorers [],
  :name "ThaiChain",
  :faucets [],
  :shortName "tch",
  :chainId 7,
  :chain "TCH",
  :network "mainnet",
  :infoURL "https://thaichain.io",
  :networkId 7}
 {:rpc
  ["https://volta-rpc.energyweb.org"
   "wss://volta-rpc.energyweb.org/ws"],
  :nativeCurrency {:name "Volta Token", :symbol "VT", :decimals 18},
  :explorers [],
  :name "Energy Web Volta Testnet",
  :faucets ["https://voltafaucet.energyweb.org"],
  :shortName "vt",
  :chainId 73799,
  :chain "Volta",
  :network "testnet",
  :infoURL "https://energyweb.org",
  :networkId 73799}
 {:rpc ["https://rpc2.mix-blockchain.org:8647"],
  :nativeCurrency {:name "Mix Ether", :symbol "MIX", :decimals 18},
  :explorers [],
  :name "Mix",
  :faucets [],
  :shortName "mix",
  :chainId 76,
  :chain "MIX",
  :network "mainnet",
  :infoURL "https://mix-blockchain.org",
  :networkId 76}
 {:rpc
  ["https://sokol.poa.network"
   "wss://sokol.poa.network/wss"
   "ws://sokol.poa.network:8546"],
  :nativeCurrency
  {:name "POA Sokol Ether", :symbol "POA", :decimals 18},
  :explorers [],
  :name "POA Network Sokol",
  :faucets ["https://faucet-sokol.herokuapp.com"],
  :shortName "poa",
  :chainId 77,
  :chain "POA",
  :network "sokol",
  :infoURL "https://poa.network",
  :networkId 77}
 {:rpc ["https://mewapi.musicoin.tw"],
  :nativeCurrency {:name "Musicoin", :symbol "MUSIC", :decimals 18},
  :explorers [],
  :name "Musicoin",
  :faucets [],
  :shortName "music",
  :chainId 7762959,
  :chain "MUSIC",
  :network "mainnet",
  :infoURL "https://musicoin.tw",
  :networkId 7762959}
 {:rpc ["http://54.210.246.165:8545"],
  :nativeCurrency {:name "Photon", :symbol "Photon", :decimals 18},
  :explorers [],
  :name "Ethermint Testnet",
  :faucets [],
  :shortName "emint",
  :chainId 777,
  :chain "ETHERMINT",
  :network "testnet",
  :infoURL "https://docs.ethermint.zone",
  :networkId 777}
 {:rpc ["https://ethnode.primusmoney.com/mainnet"],
  :nativeCurrency {:name "Primus Ether", :symbol "PETH", :decimals 18},
  :explorers [],
  :name "PrimusChain mainnet",
  :faucets [],
  :shortName "primuschain",
  :chainId 78,
  :chain "PC",
  :network "mainnet",
  :infoURL "https://primusmoney.com",
  :networkId 78}
 {:rpc ["https://ethnode.primusmoney.com/firenze"],
  :nativeCurrency {:name "Firenze Ether", :symbol "FIN", :decimals 18},
  :explorers [],
  :name "Firenze test network",
  :faucets [],
  :shortName "firenze",
  :chainId 78110,
  :chain "ETH",
  :network "testnet",
  :infoURL "https://primusmoney.com",
  :networkId 78110}
 {:rpc [],
  :nativeCurrency {:name "Acala Token", :symbol "ACA", :decimals 18},
  :explorers [],
  :name "Acala Network",
  :faucets [],
  :shortName "aca",
  :chainId 787,
  :chain "ACA",
  :network "mainnet",
  :infoURL "https://acala.network",
  :networkId 787}
 {:rpc ["https://rpc.octano.dev" "https://pyrus2.ubiqscan.io"],
  :nativeCurrency {:name "Ubiq Ether", :symbol "UBQ", :decimals 18},
  :explorers [],
  :name "Ubiq Network Mainnet",
  :faucets [],
  :shortName "ubq",
  :chainId 8,
  :chain "UBQ",
  :network "mainnet",
  :infoURL "https://ubiqsmart.com",
  :networkId 88}
 {:rpc
  ["https://rpc-mumbai.matic.today" "wss://ws-mumbai.matic.today"],
  :nativeCurrency {:name "Matic", :symbol "tMATIC", :decimals 18},
  :explorers [],
  :name "Matic Testnet Mumbai",
  :faucets ["https://faucet.matic.network/"],
  :shortName "maticmum",
  :chainId 80001,
  :chain "Matic",
  :network "testnet",
  :infoURL "https://matic.network/",
  :networkId 80001}
 {:rpc ["https://rpc.meter.io"],
  :nativeCurrency {:name "Meter", :symbol "MTR", :decimals 18},
  :explorers [],
  :name "Meter Mainnet",
  :faucets [],
  :shortName "Meter",
  :chainId 82,
  :chain "METER",
  :network "mainnet",
  :infoURL "https://www.meter.io",
  :networkId 82}
 {:rpc ["https://clo-geth.0xinfra.com"],
  :nativeCurrency
  {:name "Callisto Mainnet Ether", :symbol "CLO", :decimals 18},
  :explorers [],
  :name "Callisto Mainnet",
  :faucets [],
  :shortName "clo",
  :chainId 820,
  :chain "CLO",
  :network "mainnet",
  :infoURL "https://callisto.network",
  :networkId 1}
 {:rpc [],
  :nativeCurrency
  {:name "Callisto Testnet Ether", :symbol "TCLO", :decimals 18},
  :explorers [],
  :name "Callisto Testnet",
  :faucets [],
  :shortName "tclo",
  :chainId 821,
  :chain "CLO",
  :network "testnet",
  :infoURL "https://callisto.network",
  :networkId 2}
 {:rpc ["https://node-api.klaytnapi.com/v1/klaytn"],
  :nativeCurrency {:name "KLAY", :symbol "KLAY", :decimals 18},
  :explorers [],
  :name "Klaytn Mainnet Cypress",
  :faucets [],
  :shortName "Cypress",
  :chainId 8217,
  :chain "KLAY",
  :network "cypress",
  :infoURL "https://www.klaytn.com/",
  :networkId 8217}
 {:rpc ["https://www.krotho-test.net"],
  :nativeCurrency {:name "Kortho Test", :symbol "KTO", :decimals 11},
  :explorers [],
  :name "KorthoTest",
  :faucets [],
  :shortName "Kortho",
  :chainId 8285,
  :chain "Kortho",
  :network "Test",
  :infoURL "https://www.kortho.io/",
  :networkId 8285}
 {:rpc ["https://rpc.tomochain.com"],
  :nativeCurrency
  {:name "TomoChain Ether", :symbol "TOMO", :decimals 18},
  :explorers [],
  :name "TomoChain",
  :faucets [],
  :shortName "tomo",
  :chainId 88,
  :chain "TOMO",
  :network "mainnet",
  :infoURL "https://tomocoin.io",
  :networkId 88}
 {:rpc ["https://gwan-ssl.wandevs.org:56891/"],
  :nativeCurrency {:name "Wancoin", :symbol "WAN", :decimals 18},
  :explorers [],
  :name "Wanchain",
  :faucets [],
  :shortName "wan",
  :chainId 888,
  :chain "WAN",
  :network "mainnet",
  :infoURL "https://www.wanscan.org",
  :networkId 888}
 {:rpc ["https://core.bloxberg.org"],
  :nativeCurrency {:name "BERG", :symbol "U+25B3", :decimals 18},
  :explorers [],
  :name "bloxberg",
  :faucets ["https://faucet.bloxberg.org/"],
  :shortName "berg",
  :chainId 8995,
  :chain "bloxberg",
  :network "mainnet",
  :infoURL "https://bloxberg.org",
  :networkId 8995}
 {:rpc [],
  :nativeCurrency
  {:name "Ubiq Testnet Ether", :symbol "TUBQ", :decimals 18},
  :explorers [],
  :name "Ubiq Network Testnet",
  :faucets [],
  :shortName "tubq",
  :chainId 9,
  :chain "UBQ",
  :network "mainnet",
  :infoURL "https://ethersocial.org",
  :networkId 2}
 {:rpc
  ["https://data-seed-prebsc-1-s1.binance.org:8545"
   "https://data-seed-prebsc-2-s1.binance.org:8545"
   "https://data-seed-prebsc-1-s2.binance.org:8545"
   "https://data-seed-prebsc-2-s2.binance.org:8545"
   "https://data-seed-prebsc-1-s3.binance.org:8545"
   "https://data-seed-prebsc-2-s3.binance.org:8545"],
  :nativeCurrency
  {:name "Binance Chain Native Token", :symbol "tBNB", :decimals 18},
  :explorers [],
  :name "Binance Smart Chain Testnet",
  :faucets ["https://testnet.binance.org/faucet-smart"],
  :shortName "bnbt",
  :chainId 97,
  :chain "BSC",
  :network "Chapel",
  :infoURL "https://testnet.binance.org/",
  :networkId 97}
 {:rpc
  ["https://api.nepalblockchain.dev"
   "https://api.nepalblockchain.network"],
  :nativeCurrency
  {:name "Nepal Blockchain Network Ether",
   :symbol "YETI",
   :decimals 18},
  :explorers [],
  :name "Nepal Blockchain Network",
  :faucets ["https://faucet.nepalblockchain.network"],
  :shortName "yeti",
  :chainId 977,
  :chain "YETI",
  :network "mainnet",
  :infoURL "https://nepalblockchain.network",
  :networkId 977}
 {:rpc
  ["https://core.poanetwork.dev"
   "http://core.poanetwork.dev:8545"
   "https://core.poa.network"
   "ws://core.poanetwork.dev:8546"],
  :nativeCurrency
  {:name "POA Network Core Ether", :symbol "SKL", :decimals 18},
  :explorers [],
  :name "POA Network Core",
  :faucets [],
  :shortName "skl",
  :chainId 99,
  :chain "POA",
  :network "core",
  :infoURL "https://poa.network",
  :networkId 99}
 {:rpc ["https://toys.joys.cash/"],
  :nativeCurrency {:name "TOYS", :symbol "TOYS", :decimals 18},
  :explorers [],
  :name "Joys Digital TestNet",
  :faucets ["https://faucet.joys.digital/"],
  :shortName "TOYS",
  :chainId 99415706,
  :chain "TOYS",
  :network "testnet",
  :infoURL "https://joys.digital",
  :networkId 99415706}
 {:rpc ["https://gwan-ssl.wandevs.org:46891/"],
  :nativeCurrency {:name "Wancoin", :symbol "WAN", :decimals 18},
  :explorers [],
  :name "Wanchain Testnet",
  :faucets [],
  :shortName "twan",
  :chainId 999,
  :chain "WAN",
  :network "testnet",
  :infoURL "https://testnet.wanscan.org",
  :networkId 999}]
)

(def chainId->chain
  (reduce into {} (map (fn [chain] {(:chainId chain) chain}) chains)))
